name: Trigger Review Comment from Token User

on:
  pull_request:
    types: [synchronize]

jobs:
  comment-on-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check for REVIEWER_TOKEN
        id: check-token
        run: |
          if [ -z "${{ secrets.REVIEWER_TOKEN }}" ]; then
            echo "no-token=true" >> $GITHUB_OUTPUT
          else
            echo "no-token=false" >> $GITHUB_OUTPUT
          fi

      - name: Leave review comment
        if: steps.check-token.outputs.no-token == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REVIEWER_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log("No pull_request object in payload, exiting.");
              return;
            }

            // Get the token user
            const { data: tokenUser } = await github.rest.users.getAuthenticated();

            // If the PR was not created by the token user — do nothing
            if (pr.user.login !== tokenUser.login) {
              console.log(`PR #${pr.number} was created by ${pr.user.login}, not ${tokenUser.login}, skipping.`);
              return;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: "@codex make review"
            });
            console.log(`Review comment added to PR #${pr.number}`);
